AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ProvidersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'Providers'
      AttributeDefinitions:
        - AttributeName: 'ProviderID'
          AttributeType: 'S'
        - AttributeName: 'ProviderType'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'ProviderID'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: 'ProviderTypeIndex'
          KeySchema:
            - AttributeName: 'ProviderType'
              KeyType: 'HASH'
          Projection:
            ProjectionType: 'ALL'
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: 'NEW_AND_OLD_IMAGES'